const hard = [
  { name: "iceAge1", img: "images/iceAge1.jpeg" },
  { name: "iceAge2", img: "images/iceAge2.jpeg" },
  { name: "iceAge3", img: "images/iceAge3.jpeg" },
  { name: "iceAge4", img: "images/iceAge4.jpeg" },
  { name: "iceAge5", img: "images/iceAge5.jpeg" },
  { name: "iceAge6", img: "images/iceAge6.jpeg" },
  { name: "iceAge7", img: "images/iceAge7.jpeg" },
  { name: "iceAge8", img: "images/iceAge8.jpeg" },
  { name: "iceAge9", img: "images/iceAge9.jpeg" },
  { name: "iceAge1", img: "images/iceAge1.jpeg" },
  { name: "iceAge2", img: "images/iceAge2.jpeg" },
  { name: "iceAge3", img: "images/iceAge3.jpeg" },
  { name: "iceAge4", img: "images/iceAge4.jpeg" },
  { name: "iceAge5", img: "images/iceAge5.jpeg" },
  { name: "iceAge6", img: "images/iceAge6.jpeg" },
  { name: "iceAge7", img: "images/iceAge7.jpeg" },
  { name: "iceAge8", img: "images/iceAge8.jpeg" },
  { name: "iceAge9", img: "images/iceAge9.jpeg" },
];
export default hard;
